[config]
  name = "knit-compat"
  display = "Sapphire compatibility for Prvd 'M Wrong"
  description = "Implements a thin compatibility layer between Sapphire and Prvd 'M Wrong. It serves to ease transitioning to use Prvd 'M Wrong."
  dependencies = ["core"]
