#:schema ../../schemas/package.json

name = "Lumin Framework Compatibility for Prvd 'M Wrong"
description = "Drop-in Prvd 'M Wrong replacement for games that use Lumin Framework."
version = "0.2.0-rewrite.2"
dependencies = ["core"]
