[publish]
authors = ["znotfireman <znotfireman+hello@gmail.com>"]
repository = "https://github.com/prvdmwrong/prvdmwrong"
license = "MIT OR Apache-2.0"

[publish.scopes]
wally = "prvdmwrong"
pesde = "prvdmwrong"
npm = "prvdmwrong"

[docs]
sort_order = ["core"]
