site_name: Prvd 'M Wrong
site_url: https://prvdmwrong.github.io/prvdmwrong
site_description: Built on modern standards, you're simply going to build better Roblox games.
repo_name: prvdmwrong/prvdmwrong
repo_url: https://github.com/prvdmwrong/prvdmwrong

theme:
  name: material
  font:
    text: Jura
    code: JetBrains Mono
  logo: assets/wordmark
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: prvdmwrong-dark
      toggle:
        icon: octicons/sun-24
        title: Switch to light theme
    - media: "(prefers-color-scheme: light)"
      scheme: prvdmwrong-light
      toggle:
        icon: octicons/moon-24
        title: Switch to dark theme
  icon:
    top: octicons/chevron-up-24
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/flame-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    # FIXME(znotfireman): breaks customize footer
    # - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - search
    - search.suggest

plugins:
  - search
  - mike:
      alias_type: symlink
      canonical_version: null
      css_dir: css
      deploy_prefix: ""
      javascript_dir: js
      redirect_template: null
      version_selector: true

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      title: On this page
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - theme/api-reference.css
  - theme/code.css
  - theme/footer.css
  - theme/page.css
  - theme/paragraph.css
  - theme/prvdmwrong.css

extra_javascript:
  - scripts/customize.js

nav:
  - Home: index.md
  - Tutorials:
    - tutorials/index.md
  # TODO(znotfireman): Automate this... oh goodness
  - API Reference:
    - api-reference/index.md
    - Core:
      - api-reference/core/index.md
      - Providers:
        - api-reference/core/providers/index.md
        - Provider: api-reference/core/providers/types/provider.md
        - Root: api-reference/core/providers/types/root.md
        - StartRoot: api-reference/core/providers/types/startroot.md
        - prvd: api-reference/core/providers/functions/prvd.md
        - root: api-reference/core/providers/functions/root.md
      - Lifecycles:
        - api-reference/core/lifecycles/index.md
        - Lifecycle: api-reference/core/lifecycles/types/lifecycle.md
        - fireConcurrent: api-reference/core/lifecycles/functions/fireconcurrent.md
        - fireSequential: api-reference/core/lifecycles/functions/firesequential.md
        - lifecycle: api-reference/core/lifecycles/functions/lifecycle.md
        - onLifecycleDestroying: api-reference/core/lifecycles/functions/onlifecycledestroying.md
        - onRegistered: api-reference/core/lifecycles/functions/onregistered.md
        - onUnregistered: api-reference/core/lifecycles/functions/onunregistered.md
    - Knit Compat:
        - api-reference/knit-compat/index.md
