# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.33.1"
lune = "lune-org/lune@0.8.8"
rojo = "rojo-rbx/rojo@7.4.4"
stylua = "JohnnyMorganz/stylua@0.20.0"
wally = "UpliftGames/wally@0.3.2"
moonwave = "evaera/moonwave@1.1.3"
