# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
darklua = "seaofvoices/darklua@0.15.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.38.0"
lune = "lune-org/lune@0.8.9"
rojo = "rojo-rbx/rojo@7.4.4"
selene = "Kampfkarren/selene@0.27.1"
stylua = "JohnnyMorganz/stylua@2.0.2"
wally = "UpliftGames/wally@0.3.2"
# FIXME(znotfireman): rokit doesn't like moonwave
# use `cargo install moonwave` for now
# moonwave = "evaera/moonwave@1.1.3"
