[config]
name = "More lifecycles for Prvd 'M Wrong"
module = "prvdLifecycles"
description = "An assortment of useful provider lifecycles for Prvd 'M Wrong."
dependencies = ["core"]

types = []

[docs]
classes = []
overview = """"""
