[config]
name = "Prvd 'M Wrong"
module = "prvd"

[config.description]
brief = "Build better games."
technical = "Core Prvd 'M Wrong functionality including providers, lifecycles, and module roots along with built-in components and networking libraries."

[config.docs]
classes = ["Providers", "Lifecycles"]
