name = "Knit Compatibility for Prvd 'M Wrong"
description = "Drop-in Prvd 'M Wrong replacement for games that use Knit."
version = "0.2.0-rewrite.1"
dependencies = ["core"]

[docs]
classes = []
overview = """"""
